specVersion: 1.0.0
name: subql
version: 0.0.1
runner:
  node:
    name: "@subql/node-cosmos"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: >-
  Subql Project for White Whale Furnace leader board

schema:
  file: ./schema.graphql

network:
  chainId: local-1
  # This endpoint must be a public non-pruned archive node
  # We recommend providing more than one endpoint for improved reliability, performance, and uptime
  # Public nodes may be rate limited, which can affect indexing speed
  # When developing your project we suggest getting a private API key
  # You can get them from OnFinality for free https://app.onfinality.io
  # https://documentation.onfinality.io/support/the-enhanced-api-service
  endpoint: http://local-migaloo:26657
  # Optionally provide the HTTP endpoint of a full chain dictionary to speed up processing
  # chainTypes: # This is a beta feature that allows support for any Cosmos chain by importing the correct protobuf messages
  #  cosmos.slashing.v1beta1:
  #    file: "./proto/cosmos/slashing/v1beta1/tx.proto"
  #    messages:
  #     - "MsgUnjail"
dataSources:
  - kind: cosmos/Runtime
    startBlock: 0 # first block on the fourth iteration of juno
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleSumBurn
          kind: cosmos/EventHandler
          filter:
            type: execute
        - handler: handleEvent
          kind: cosmos/EventHandler
          filter:
            type: execute
#            messageFilter:
#              type: "/cosmwasm.wasm.v1.MsgExecuteContract"
#              # contractCall field can be specified here too
#              values: # A set of key/value pairs that are present in the message data
#                contract: "migaloo17p9rzwnnfxcjp32un9ug7yhhzgtkhvl9jfksztgw5uh69wac2pgsqfhjvq"
